language: ruby
cache: bundler
bundler_args: --without tools
after_success:
  - "[ -d coverage ] && bundle exec codeclimate-test-reporter"
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - truffleruby
  - ruby-head
matrix:
  include:
    - rvm: jruby-9.2.8.0
      jdk: openjdk8
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
notifications:
  email: false
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
